// <auto-generated />
using System;
using Gho_Daung___Order___Inventory_System__.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gho_Daung___Order___Inventory_System__.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gho_Daung___Order___Inventory_System__.Models.Inventory", b =>
                {
                    b.Property<int>("Inventory_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Inventory_Id"));

                    b.Property<int>("Product_Id")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Inventory_Id");

                    b.HasIndex("Product_Id")
                        .IsUnique();

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Inventory_Id = 1,
                            Product_Id = 1,
                            Quantity = 500
                        },
                        new
                        {
                            Inventory_Id = 2,
                            Product_Id = 2,
                            Quantity = 250
                        },
                        new
                        {
                            Inventory_Id = 3,
                            Product_Id = 3,
                            Quantity = 15
                        },
                        new
                        {
                            Inventory_Id = 4,
                            Product_Id = 4,
                            Quantity = 300
                        },
                        new
                        {
                            Inventory_Id = 5,
                            Product_Id = 5,
                            Quantity = 50
                        },
                        new
                        {
                            Inventory_Id = 6,
                            Product_Id = 6,
                            Quantity = 40
                        },
                        new
                        {
                            Inventory_Id = 7,
                            Product_Id = 7,
                            Quantity = 120
                        },
                        new
                        {
                            Inventory_Id = 8,
                            Product_Id = 8,
                            Quantity = 200
                        },
                        new
                        {
                            Inventory_Id = 9,
                            Product_Id = 9,
                            Quantity = 350
                        },
                        new
                        {
                            Inventory_Id = 10,
                            Product_Id = 10,
                            Quantity = 25
                        },
                        new
                        {
                            Inventory_Id = 11,
                            Product_Id = 11,
                            Quantity = 100
                        },
                        new
                        {
                            Inventory_Id = 12,
                            Product_Id = 12,
                            Quantity = 180
                        },
                        new
                        {
                            Inventory_Id = 13,
                            Product_Id = 13,
                            Quantity = 75
                        },
                        new
                        {
                            Inventory_Id = 14,
                            Product_Id = 14,
                            Quantity = 60
                        });
                });

            modelBuilder.Entity("Gho_Daung___Order___Inventory_System__.Models.Order", b =>
                {
                    b.Property<int>("Order_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Order_Id"));

                    b.Property<DateTime>("Order_Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Order_Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Gho_Daung___Order___Inventory_System__.Models.OrderItem", b =>
                {
                    b.Property<int>("Order_Id")
                        .HasColumnType("int");

                    b.Property<int>("Product_Id")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Price_At_Purchase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Order_Id", "Product_Id");

                    b.HasIndex("Product_Id");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Gho_Daung___Order___Inventory_System__.Models.Product", b =>
                {
                    b.Property<int>("Product_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Product_Id"));

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Modified_Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Product_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Product_Id");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Product_Id = 1,
                            Created_Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Price = 4.50m,
                            Product_Name = "Concrete Blocks",
                            SKU = "WH-CONC-001"
                        },
                        new
                        {
                            Product_Id = 2,
                            Created_Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Price = 12.00m,
                            Product_Name = "Steel Rebar Rods",
                            SKU = "WH-STEL-002"
                        },
                        new
                        {
                            Product_Id = 3,
                            Created_Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Price = 150.00m,
                            Product_Name = "Heavy Duty Forklift Tires",
                            SKU = "WH-TIRE-003"
                        },
                        new
                        {
                            Product_Id = 4,
                            Created_Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Price = 8.00m,
                            Product_Name = "Cement Bags 50kg",
                            SKU = "WH-CEMT-004"
                        },
                        new
                        {
                            Product_Id = 5,
                            Created_Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Price = 35.00m,
                            Product_Name = "Construction Sand (Ton)",
                            SKU = "WH-SAND-005"
                        },
                        new
                        {
                            Product_Id = 6,
                            Created_Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Price = 45.00m,
                            Product_Name = "Gravel Stone (Ton)",
                            SKU = "WH-GRAV-006"
                        },
                        new
                        {
                            Product_Id = 7,
                            Created_Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Price = 25.00m,
                            Product_Name = "Wooden Pallets",
                            SKU = "WH-PALT-007"
                        },
                        new
                        {
                            Product_Id = 8,
                            Created_Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Price = 18.00m,
                            Product_Name = "Safety Helmets",
                            SKU = "WH-SAFE-008"
                        },
                        new
                        {
                            Product_Id = 9,
                            Created_Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Price = 6.50m,
                            Product_Name = "Industrial Gloves",
                            SKU = "WH-GLOV-009"
                        },
                        new
                        {
                            Product_Id = 10,
                            Created_Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Price = 120.00m,
                            Product_Name = "Electric Drill Machine",
                            SKU = "WH-TOOL-010"
                        },
                        new
                        {
                            Product_Id = 11,
                            Created_Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Price = 55.00m,
                            Product_Name = "Steel Pipes",
                            SKU = "WH-PIPE-011"
                        },
                        new
                        {
                            Product_Id = 12,
                            Created_Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Price = 20.00m,
                            Product_Name = "PVC Water Pipes",
                            SKU = "WH-PVC-012"
                        },
                        new
                        {
                            Product_Id = 13,
                            Created_Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Price = 40.00m,
                            Product_Name = "Paint Bucket 20L",
                            SKU = "WH-PAIN-013"
                        },
                        new
                        {
                            Product_Id = 14,
                            Created_Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Price = 30.00m,
                            Product_Name = "LED Warehouse Lights",
                            SKU = "WH-LITE-014"
                        });
                });

            modelBuilder.Entity("Gho_Daung___Order___Inventory_System__.Models.Inventory", b =>
                {
                    b.HasOne("Gho_Daung___Order___Inventory_System__.Models.Product", "Product")
                        .WithOne("Inventory")
                        .HasForeignKey("Gho_Daung___Order___Inventory_System__.Models.Inventory", "Product_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Gho_Daung___Order___Inventory_System__.Models.OrderItem", b =>
                {
                    b.HasOne("Gho_Daung___Order___Inventory_System__.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("Order_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gho_Daung___Order___Inventory_System__.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Product_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Gho_Daung___Order___Inventory_System__.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Gho_Daung___Order___Inventory_System__.Models.Product", b =>
                {
                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
